# -*- coding: utf-8 -*-
"""tipu tipu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_YDW9ios-bpTaL1apaUeS735X9dlFEa
"""

print('Halo Rek !')
print('Belajar AI')
print('Yes')