# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kiSt9aCaciMXnBz8i4m-E7pRGNmVwZ29
"""

from flask import Flask, render_template, url_for, request

application = Flask(_name_)

@application.route('/',methods=['GET','POST'])
def index():
    if request.method=='POST':
        tinggibadan = request.form['tinggi']
        jeniskelamin = request.form['jenis']
        return render_template('tampil.html',tinggibadan=tinggi,jeniskelamin=jenis)
    return render_template('index.html')

if _name_ == '_main_':
    application.run(debug=True)